### ISSUE TITLE
Updated main.ts to Svelte5 syntax

### ISSUE THREAD

**Issue by Acumen-Desktop** [ArcherGu/vite-svelte-nestjs-electron#227]
I made this change to render/main.ts:

```javascript
import './app.css'
import App from './App.svelte'
import { mount } from 'svelte'

mount(App, {
  target: document.getElementById('app')!,
})

export default App`
```
Seems to work better.

Now I am interested in converting the render to sveltekit.

**Comment by ArcherGu** [comment]
You can make any changes in the render layer or replace any framework, I'm just providing an example. Actually, this part of the code is provided by vite's svelte template. 🙂You can also provide a PR, let's upgrade it together.
